driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.17.44
  data_bags_path: "data_bags"
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[pjc_base::default]
