---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.17.44

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[pjc_base::default]
