---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.17.44
  always_update_cookbooks: true
  data_bags_path: test/data_bags

platforms:
  #- name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[pjc_base::default]
    attributes:
      pjc_base:
        include_all: true
        include_scl_repo: true
