---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

suites:
  - name: default
    driver:
      vm_hostname: kitchen.lan.chicarello.com
    run_list:
      - recipe[homelan::default]
