name 'pjc_base'
maintainer 'Paul Chicarello'
maintainer_email 'paul@chicarello.com'
issues_url 'https://github.com/rumdawgg/chef-pjc_base/issues'
source_url 'https://github.com/rumdawgg/chef-pjc_base'
license 'Apache-2.0'
description 'Configures a node on the lan.chicarello.com domain'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.4.0'
chef_version '>= 12.7' if respond_to?(:chef_version)

supports 'ubuntu', '>= 14.04'
supports 'debian', '>= 7.0'
supports 'centos', '>= 6.0'
supports 'redhat'

depends 'apt', '~> 7.1.0'
depends 'chef-client', '~> 11.0.1'
depends 'logrotate', '~> 2.2.0'
depends 'openssh', '~> 2.7.0'
depends 'rsyslog', '~> 6.0.7'
depends 'selinux', '~> 2.1.1'
depends 'ssh_authorized_keys', '~> 0.4.0'
depends 'sudo', '~> 5.4.2'
depends 'ubuntu', '~> 2.0.1'
depends 'users', '~> 5.4.0'
depends 'yum', '~> 5.1.0'
depends 'yum-epel', '~> 3.2.0'
depends 'yum-centos', '~> 3.0.0'
