name 				      'pjc-base'
maintainer 			  'Paul Chicarello'
maintainer_email 	'paul@chicarello.com'
license 			    'All rights reserved'
description 		  'Configures a node on the lan.chicarello.com domain'
long_description 	'Configures a node on the lan.chicarello.com domain'
version           '0.2.0'

depends 'apt'
depends 'build-essential'
depends 'chef-client'
depends 'openssh'
depends 'rsyslog'
depends 'ssh-keys'
depends 'sudo'
depends 'users'
depends 'yum-epel'
