name 				'homelan'
maintainer 			'Paul Chicarello'
maintainer_email 	'paul@chicarello.com'
license 			'All rights reserved'
description 		'Configures a node on the lan.chicarello.com domain'
long_description 	'Configures a node on the lan.chicarello.com domain'
version 			'0.1.27'

depends 'chef-client', '~> 4.3.3'
depends 'users', '~> 2.0.3'
depends 'openssh', '~> 1.6.1'
depends 'build-essential', '~> 2.3.1'
depends 'sudo', '~> 2.9.0'
depends 'ssh-keys', '~> 1.2.7'
depends 'rsyslog', '~> 4.0.0'
depends 'apt', '~> 2.9.2'
depends 'yum-epel', '~> 0.6.6'
